version: '3.8'
services:
  db-master:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: formulario
    ports:
      - "3307:3306"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d

  db-slave:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_REPLICATION_USER: repl_user
      MYSQL_REPLICATION_PASSWORD: repl_password
    depends_on:
      - db-master

  app1:
    build:
      context: .
    ports:
      - "7501:7501"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7501"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always  # Reinicio automático
    depends_on:
      - db-master
    links:
      - db-master
    networks:
      - app_network
   
  app2:
    build:
      context: .
    ports:
      - "7502:7501"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7501"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always  # Reinicio automático
    depends_on:
      - db-master
    links:
      - db-master
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
    networks:
      - app_network

networks:
  app_network:
    driver: bridge